OpenLMIS/openlmis-requisition

docker-compose.builder.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/6)

OLMIS-651: added db link to pass integration tests

---

src/integration-test/java/org/openlmis/referencedata/repository/OrderLineRepositoryIT.java
src/main/java/org/openlmis/referencedata/domain/Order.java
src/main/java/org/openlmis/referencedata/domain/OrderLine.java
src/main/java/org/openlmis/referencedata/repository/OrderLineRepository.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/4)

OLMIS-660 Add Line Items to an existing Order

---

src/integration-test/java/org/openlmis/referencedata/repository/BaseCrudRepositoryIT.java
src/integration-test/java/org/openlmis/referencedata/repository/FacilityRepositoryIT.java
src/integration-test/java/org/openlmis/referencedata/repository/OrderLineRepositoryIT.java
src/integration-test/java/org/openlmis/referencedata/repository/OrderRepositoryIT.java
src/integration-test/java/org/openlmis/referencedata/repository/ProductRepositoryIT.java
src/integration-test/java/org/openlmis/referencedata/repository/ProgramRepositoryIT.java
src/integration-test/java/org/openlmis/referencedata/repository/UserRepositoryIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/7)

OLMIS-660 Fix failing integration tests

---

README.md
build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/8)

OLMIS-732: Sonar: projects for current v3 repositories

---

docker-compose.yml

@jkondrat, this is what I was thinking of when I mentioned nginx in docker dev environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/10)

OLMIS-761, add nginx to development environment

---

demo-data/requisition.columns_maps.json

Yo! I don't have access — merge this! (or give me access and I'll just push it)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/14)

Updated requisition templates to have columns with calculated fields

---

src/main/java/org/openlmis/requisition/dto/FacilityDto.java
src/main/java/org/openlmis/requisition/service/referencedata/FacilityReferenceDataService.java

Following the changes in referencedata, the requisition service
has been updated to work with the changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/17)

Added support for new facilities search

---

src/main/java/org/openlmis/requisition/domain/JasperTemplateParameter.java
src/main/java/org/openlmis/requisition/dto/JasperTemplateParameterDto.java
src/main/java/org/openlmis/requisition/service/JasperTemplateService.java
src/main/resources/db/migration/20170411152555231__create_jaspertemplateparameter_options_table.sql
src/main/resources/schemas/jasperTemplateParameterDto.json
src/test/java/org/openlmis/requisition/service/JasperTemplateServiceTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/18)

Add possibility to define filter options in a Jasper template parameter

---

demo-data/requisition.requisitions.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/22)

Fix duplicate requisition in demo data

---

src/integration-test/java/org/openlmis/requisition/repository/RequisitionRepositoryIntegrationTest.java
src/main/java/org/openlmis/requisition/repository/custom/impl/RequisitionRepositoryImpl.java

According to the query execution plan, joining the status_changes
table takes most of the time in those queries (which makes sense,
considering that status_changes table will be several times bigger
than the requisitions). Since we only need created date which
is also kept in the requisition, we remove joins and use direct
field from requisition instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/27)

Remove status changes join from requisition queries

---

src/main/java/org/openlmis/requisition/domain/AvailableRequisitionColumn.java
src/main/java/org/openlmis/requisition/domain/JasperTemplateParameter.java
src/main/java/org/openlmis/requisition/domain/Requisition.java
src/main/java/org/openlmis/requisition/domain/RequisitionLineItem.java
src/main/java/org/openlmis/requisition/domain/RequisitionTemplate.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/32)

MW-309: Change collections to use lazy FetchMode

---

src/main/java/org/openlmis/requisition/domain/Requisition.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/35)

MW-309: Fix availableNonFullSupplyProducts not initiating properly

---

src/main/java/org/openlmis/requisition/domain/Requisition.java
src/test/java/org/openlmis/requisition/domain/RequisitionTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/34)

MW-309: Use a map of orderableId to lineItem instead of nested iteration

---

src/main/java/org/openlmis/CustomWebMvcConfigurerAdapter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/39)

MW-412: CORS support

---

src/integration-test/java/org/openlmis/requisition/web/BatchRequisitionControllerIntegrationTest.java
src/main/resources/api-definition.yaml
src/main/resources/schemas/approveRequisitionDto.json
src/main/resources/schemas/approveRequisitionLineItemDto.json

https://openlmis.atlassian.net/browse/OLMIS-3237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/45)

MW-623: Check schema validity in BatchRequisitionController ITs

---

src/integration-test/java/org/openlmis/requisition/web/BatchRequisitionControllerIntegrationTest.java
src/integration-test/java/org/openlmis/requisition/web/RequisitionControllerIntegrationTest.java
src/main/java/org/openlmis/requisition/exception/ContentNotFoundMessageException.java
src/main/java/org/openlmis/requisition/service/PermissionService.java
src/main/java/org/openlmis/requisition/service/RequisitionService.java
src/main/java/org/openlmis/requisition/utils/DatePhysicalStockCountCompletedEnabledPredicate.java
src/main/java/org/openlmis/requisition/web/BaseRequisitionController.java
src/main/java/org/openlmis/requisition/web/BatchRequisitionController.java
src/main/java/org/openlmis/requisition/web/RequisitionController.java
src/main/java/org/openlmis/requisition/web/RequisitionDtoBuilder.java
src/test/java/org/openlmis/requisition/service/PermissionServiceTest.java
src/test/java/org/openlmis/requisition/service/RequisitionServiceTest.java
src/test/java/org/openlmis/requisition/utils/DatePhysicalStockCountCompletedEnabledPredicateTest.java
src/test/java/org/openlmis/requisition/web/RequisitionControllerTest.java
src/test/java/org/openlmis/requisition/web/RequisitionDtoBuilderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/47)

OLMIS-4383: Decreased number of db/external service calls

---

src/main/java/org/openlmis/requisition/CustomWebMvcConfigurerAdapter.java

This fix refers to https://openlmis.atlassian.net/browse/AO-278
It's about a unification of the OpenLMIS endpoints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/48)

OLMIS-6332: Change page size of requisitions search to max int

---

CHANGELOG.md
gradle.properties
src/main/java/org/openlmis/requisition/service/ApprovalNotifier.java
src/main/java/org/openlmis/requisition/service/ApprovedRequisitionNotifier.java
src/main/java/org/openlmis/requisition/service/RequisitionStatusNotifier.java
src/main/resources/application.properties
src/test/java/org/openlmis/requisition/service/ApprovedRequisitionNotifierTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/49)

OLMIS-6558: Introduce new env variable - PUBLIC_URL

---

CHANGELOG.md
src/main/java/org/openlmis/requisition/validate/RequisitionTemplateDtoValidator.java
src/test/java/org/openlmis/requisition/validate/RequisitionTemplateDtoValidatorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/54)

OLMIS-6793: removed validation for calculated order quantity ISA

---

src/integration-test/java/org/openlmis/requisition/web/RequisitionControllerIntegrationTest.java
src/main/java/org/openlmis/requisition/domain/Rejection.java
src/main/java/org/openlmis/requisition/domain/requisition/StatusChange.java
src/main/java/org/openlmis/requisition/dto/RejectionDto.java
src/main/java/org/openlmis/requisition/dto/StatusChangeDto.java
src/main/java/org/openlmis/requisition/i18n/MessageKeys.java
src/main/java/org/openlmis/requisition/repository/RejectionRepository.java
src/main/java/org/openlmis/requisition/service/RequisitionService.java
src/main/java/org/openlmis/requisition/web/RequisitionController.java
src/main/resources/api-definition.yaml
src/main/resources/db/migration/20201117130741211__schema_for_requisition_rejection_table.sql
src/main/resources/messages_en.properties
src/main/resources/schemas/rejectionDto.json
src/test/java/org/openlmis/requisition/service/RequisitionServiceTest.java
src/test/java/org/openlmis/requisition/testutils/RejectionDataBuilder.java
src/test/java/org/openlmis/requisition/web/RequisitionControllerTest.java

Backend script to store requisition rejection reasons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/58)

TZUP-156: Backend to store reason for R&R been rejected  2e58624

---

src/integration-test/java/org/openlmis/requisition/web/RequisitionControllerIntegrationTest.java
src/main/java/org/openlmis/requisition/dto/RejectionDto.java
src/main/java/org/openlmis/requisition/service/RequisitionService.java
src/test/java/org/openlmis/requisition/testutils/RejectionDataBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/59)

Tzupgrade rejection reason

---

CHANGELOG.md
src/integration-test/java/org/openlmis/requisition/repository/RequisitionTemplateRepositoryIntegrationTest.java
src/integration-test/java/org/openlmis/requisition/web/RequisitionTemplateControllerIntegrationTest.java
src/main/java/org/openlmis/requisition/domain/RequisitionTemplate.java
src/main/java/org/openlmis/requisition/domain/RequisitionTemplateAssignment.java
src/main/java/org/openlmis/requisition/dto/BasicRequisitionTemplateDto.java
src/main/java/org/openlmis/requisition/dto/RequisitionTemplateDto.java
src/main/java/org/openlmis/requisition/repository/RequisitionTemplateRepository.java
src/main/java/org/openlmis/requisition/service/RequisitionTemplateService.java
src/main/java/org/openlmis/requisition/validate/RequisitionTemplateDtoValidator.java
src/main/resources/db/migration/20221219073916071__add_requisition_report_only_to_requisition_template_assignments.sql
src/main/resources/db/migration/20221221100926211__add_requisition_reporting_only_flag_to_requisition_template_table.sql
src/main/resources/schemas/requisitionTemplate.json
src/test/java/org/openlmis/requisition/domain/RequisitionTemplateDataBuilder.java
src/test/java/org/openlmis/requisition/domain/RequisitionTemplateTest.java
src/test/java/org/openlmis/requisition/dto/RequisitionTemplateDtoTest.java
src/test/java/org/openlmis/requisition/service/RequisitionTemplateServiceTest.java
src/test/java/org/openlmis/requisition/validate/RequisitionTemplateDtoValidatorTest.java

This the backend code for the TZUP-274: requisition report only functionality
[TZUP-274]: https://openlmis.atlassian.net/browse/TZUP-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlmis/openlmis-requisition/62)

TZUP-274:-This is the backend code to support requisition only flag on requisition template

---

CHANGELOG.md
src/main/java/org/openlmis/requisition/web/FacilitySupportsProgramHelper.java
src/main/java/org/openlmis/requisition/web/RequisitionController.java
src/test/java/org/openlmis/requisition/web/FacilitySupportsProgramHelperTest.java
src/test/java/org/openlmis/requisition/web/RequisitionControllerTest.java

Added optional query param for GET /api/requisitions/periodsForInitiate endpoint
Jira task link: https://openlmis.atlassian.net/browse/OLMIS-7625
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/63)

OLMIS-7625: Fixed setting Start Date for a specific program in a specific facility

---

build.gradle
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/68)

Fixed gradle build

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/72)

Gradle check and pmd plugins before tests

---

Jenkinsfile

this is temporary solution, currently contract tests does not work for couple months
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/73)

Disable contract tests

---

src/main/java/org/openlmis/requisition/service/referencedata/UserRoleAssignmentsReferenceDataService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/74)

OLMIS-7723: Update User Roles Service after Sonar analysis

---

src/main/java/org/openlmis/requisition/web/RequisitionController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/84)

TZUP-565 Disable sending a stock event when patients tab is enabled

---

src/main/java/org/openlmis/requisition/service/referencedata/UserRoleAssignmentsReferenceDataService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/87)

OLMIS-7802: Fix error related to second approval

---

src/integration-test/java/org/openlmis/requisition/repository/RequisitionRepositoryIntegrationTest.java
src/integration-test/java/org/openlmis/requisition/web/RequisitionControllerIntegrationTest.java
src/main/java/org/openlmis/requisition/repository/custom/RequisitionRepositoryCustom.java
src/main/java/org/openlmis/requisition/repository/custom/impl/RequisitionRepositoryImpl.java
src/main/java/org/openlmis/requisition/service/RequisitionService.java
src/main/java/org/openlmis/requisition/web/RequisitionController.java
src/main/resources/api-definition.yaml
src/test/java/org/openlmis/requisition/service/RequisitionServiceTest.java

JIRA task link: https://openlmis.atlassian.net/browse/SELV3-705
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/91)

SELV3-705: Added GET api/requisitions/numberOfRequisitionsForApprova endpoint

---

src/integration-test/java/org/openlmis/requisition/repository/RequisitionRepositoryIntegrationTest.java
src/integration-test/java/org/openlmis/requisition/web/RequisitionControllerIntegrationTest.java
src/main/java/org/openlmis/requisition/repository/custom/RequisitionRepositoryCustom.java
src/main/java/org/openlmis/requisition/repository/custom/impl/RequisitionRepositoryImpl.java
src/main/java/org/openlmis/requisition/service/RequisitionService.java
src/main/java/org/openlmis/requisition/web/RequisitionController.java
src/main/resources/api-definition.yaml
src/test/java/org/openlmis/requisition/service/RequisitionServiceTest.java

JIRA task link: https://openlmis.atlassian.net/browse/SELV3-718
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/92)

SELV3-718: Added new filters to Approve Requisitions page

---

src/main/resources/db/migration/20240314174732705__add_requisition_indexes.sql

Jira link: https://openlmis.atlassian.net/browse/OLMIS-7858
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/94)

OLMIS-7858: Add four indexes on requisition schema

---

src/main/resources/db/migration/20240404095644746__update_dosesPerPatient_column_source.sql

JIRA task link: https://openlmis.atlassian.net/browse/OLMIS-7860
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/96)

OLMIS-7860: Changed dosesPerPatient column source

---

gradle.properties

Corrected properties for the release name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/100)

release properties correction

---

src/integration-test/java/org/openlmis/requisition/web/BaseWebIntegrationTest.java
src/integration-test/java/org/openlmis/requisition/web/BatchRequisitionControllerIntegrationTest.java
src/main/java/org/openlmis/requisition/i18n/MessageKeys.java
src/main/java/org/openlmis/requisition/web/BaseRequisitionController.java
src/main/java/org/openlmis/requisition/web/BatchRequisitionController.java
src/main/java/org/openlmis/requisition/web/FacilityTypeHelper.java
src/main/resources/messages_en.properties
src/test/java/org/openlmis/requisition/web/BatchRequisitionControllerTest.java
src/test/java/org/openlmis/requisition/web/FacilitySupportsProgramHelperTest.java
src/test/java/org/openlmis/requisition/web/FacilityTypeHelperTest.java
src/test/java/org/openlmis/requisition/web/RequisitionControllerTest.java

JIRA task link: https://openlmis.atlassian.net/browse/OAM-184
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/101)

OAM-184: Added validation for Wards/Services in requisition functions

---

build.sh
docker-compose.builder.yml
docker-compose.override.yml

Changed --resource value
Updated the version of docker-dev used to v9
JIRA task link: https://openlmis.atlassian.net/browse/OIS-14
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/102)

OIS-14: Added configuration for Transifex CLI usage

---

Dockerfile
docker-compose.builder.yml
docker-compose.erd-generation.yml
docker-compose.override.yml

JIRA task link: https://openlmis.atlassian.net/browse/OIS-48
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/104)

OIS-48: Updated dev and service-base image version

---

src/main/resources/jasperTemplates/requisition.jrxml
src/main/resources/jasperTemplates/requisitionLines.jrxml

Added fields:
- No of Patients on Treatment next month (C)
- Total Requirement (E) E = C * D
- Total Quantity Needed by HF (F) F = E * 2
- Quantity to issue (G) G = F - A 
- Quantity to issue (converted to unit of measure) G/U
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/106)

OLMIS-7923 Add missing fields to requisition prints

---

CHANGELOG.md
src/main/java/org/openlmis/requisition/service/PeriodService.java
src/test/java/org/openlmis/requisition/service/PeriodServiceTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/110)

OLMIS-8066: Incorrect period name for emergency requisitions

---

CHANGELOG.md
gradle.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/113)

Release 8.4.0

---

CHANGELOG.md
src/main/java/org/openlmis/requisition/web/BaseRequisitionController.java
src/main/java/org/openlmis/requisition/web/RequisitionController.java
src/main/java/org/openlmis/requisition/web/RequisitionV2Controller.java
src/test/java/org/openlmis/requisition/web/RequisitionControllerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/OpenLMIS/openlmis-requisition/115)

OPSD-40: Allow skipping date validation when updating requisition
